name: Build Wheels
on:
  push:
  pull_request:
    branches: [master]

jobs:
  tests:
    name: Build On ${{ matrix.arch }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x64,x86]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: ${{ matrix.arch }}
      - name: Install Requirements
        run: |
          pip install -r packaging/requirements.txt
      - name: Install DejaVu, Pango and Ghostscript (Windows)
        run: |
          C:\msys64\usr\bin\bash -lc 'pacman -S mingw-w64-x86_64-ttf-dejavu mingw-w64-x86_64-pango mingw-w64-x86_64-ghostscript --noconfirm'
          xcopy "C:\msys64\mingw64\share\fonts\TTF" "C:\Users\runneradmin\.fonts" /e /i
          echo "C:\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH
          rm C:\msys64\mingw64\bin\python.exe
      - name: Build
        shell: pwsh
        run: |
          python packaging/build_wheel.py $PWD\wheelhouse
      
      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*
          name: wheels
