name: Build Wheels
on:
  push:
  pull_request:
    branches: [master]

jobs:
  tests:
    name: Build On ${{ matrix.arch }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x64,x86]
        include:
          - arch: x64
            platform_id: x86_64
            mingw: mingw64
          - arch: x86
            platform_id: i686
            mingw: mingw32
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: ${{ matrix.arch }}
      - name: Install Requirements
        run: |
          pip install -r packaging/requirements.txt
      - name: Install DejaVu, Pango and Ghostscript (Windows)
        run: |
          C:\msys64\usr\bin\bash -lc 'pacman -S mingw-w64-${{matrix.platform_id}}-ttf-dejavu mingw-w64-${{matrix.platform_id}}-pango mingw-w64-${{matrix.platform_id}}-ghostscript --noconfirm'
          xcopy "C:\msys64\${{matrix.mingw}}\share\fonts\TTF" "C:\Users\runneradmin\.fonts" /e /i
          echo "C:\msys64\${{matrix.mingw}}\bin" | Out-File -FilePath $env:GITHUB_PATH
          rm C:\msys64\${{matrix.mingw}}\bin\python.exe
      - name: Build
        shell: pwsh
        run: |
          python packaging/build_wheel.py $PWD\wheelhouse
          # remove msys2 from path
          echo "" | Out-File -FilePath $env:GITHUB_PATH
      - name: Test Wheels
        shell: pwsh
        run: |
          python -m venv _test
          _test\Scripts\activate.ps1
          pip install wheelhouse/*
          weasyprint https://weasyprint.org/ -o b.pdf
      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*
          name: wheels
